def optimize_template(html_content):
    """Optimize the HTML template generated by Folium."""
    
    # Remove unnecessary styles and add custom optimizations
    html_content = html_content.replace(
        '/* Essential styles for initial render */ .map-container { height: 100vh; width: 100%; } .loading { position: fixed; /* etc */ }',
        'Romania Highways Map'  # Custom title
    )
    
    # Split the content to insert optimizations
    head_end = html_content.find('</head>')
    body_end = html_content.find('</body>')
    
    if head_end == -1 or body_end == -1:
        return html_content
    
    # Remove blocking scripts and CSS from the original template
    blocking_resources = [
        'leaflet.awesome-markers.js',
        'jquery-3.7.1.min.js',
        'bootstrap.bundle.min.js',
        'leaflet.js',
        'leaflet.awesome-markers.css',
        'bootstrap-glyphicons.css',
        'fontawesome-free',
        'bootstrap.min.css',
        'leaflet.css',
        'leaflet.awesome.rotate.min.css'
    ]
    
    for resource in blocking_resources:
        html_content = html_content.replace(
            f'<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/{resource}"',
            f'<!-- Deferred: {resource} -->'
        )
        html_content = html_content.replace(
            f'<script src="https://cdn.jsdelivr.net/npm/{resource}"',
            f'<!-- Deferred: {resource} -->'
        )
    
    return html_content