import re


def optimize_template(html_content):
    """Optimize the HTML template generated by Folium."""

    # Remove unnecessary styles and add custom optimizations
    html_content = html_content.replace(
        "/* Essential styles for initial render */ .map-container { height: 100vh; width: 100%; } .loading { position: fixed; /* etc */ }",
        "Romania Highways Map",  # Custom title
    )

    # Split the content to insert optimizations
    head_end = html_content.find("</head>")
    body_end = html_content.find("</body>")

    if head_end == -1 or body_end == -1:
        return html_content

    # Folium injects a fixed set of CDN tags for Leaflet, jQuery, Bootstrap,
    # Leaflet.awesome-markers and FontAwesome. This project only uses Leaflet
    # (all markers are DivIcon/CircleMarker; no jQuery/Bootstrap JS or CSS
    # classes are used), so drop the unused libraries entirely and serve
    # Leaflet from a same-origin copy under assets/vendors/ (see build.py).
    # Tags are matched verbatim against what Folium emits for the pinned
    # versions; if those versions change in requirements, update these too.
    unused_tags = [
        '<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>',
        '<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>',
        '<script src="https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.js"></script>',
        '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"/>',
        '<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css"/>',
        '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.0/css/all.min.css"/>',
        '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.css"/>',
        '<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/python-visualization/folium/folium/templates/leaflet.awesome.rotate.min.css"/>',
    ]
    for tag in unused_tags:
        html_content = html_content.replace(tag, "")

    # Serve Leaflet from a same-origin copy instead of the CDN, and move the
    # script out of <head>: it was render-blocking first paint, but Folium's
    # inline map-init runs synchronously right after </body> and needs L, so it
    # can't simply be deferred. Dropping it in just after </body> (before the
    # init) lets the overlays/loading screen paint first, then Leaflet loads.
    html_content = html_content.replace(
        '<script src="https://cdn.jsdelivr.net/npm/leaflet@1.9.3/dist/leaflet.js"></script>',
        "",
    )
    html_content = html_content.replace(
        "</body>",
        '</body>\n<script src="assets/vendors/leaflet.js"></script>',
        1,
    )

    # Inline leaflet.css (small, render-blocking) to drop another request from
    # the critical path. Rewrite its relative image urls to the same-origin
    # copies so they resolve when inlined at the document root.
    try:
        with open("assets/vendors/leaflet.css", encoding="utf-8") as f:
            leaflet_css = f.read()
        leaflet_css = leaflet_css.replace("url(images/", "url(assets/vendors/images/")
        html_content = html_content.replace(
            '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet@1.9.3/dist/leaflet.css"/>',
            f"<style>{leaflet_css}</style>",
        )
    except OSError:
        # Fall back to the same-origin link if the file isn't readable.
        html_content = html_content.replace(
            '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet@1.9.3/dist/leaflet.css"/>',
            '<link rel="stylesheet" href="assets/vendors/leaflet.css"/>',
        )

    # Folium hardcodes the default Leaflet marker image URLs (iconUrl/shadowUrl)
    # to the CDN. All markers here are DivIcon/CircleMarker so these defaults are
    # not rendered, but point them at the local copies anyway to keep the page
    # fully same-origin (see assets/vendors/images/).
    html_content = html_content.replace(
        "https://cdn.jsdelivr.net/npm/leaflet@1.9.3/dist/images/",
        "assets/vendors/images/",
    )

    # The skip link targets "#map", but Folium names the map div "map_<hash>",
    # so the anchor had no target (Lighthouse: "skip links are not focusable").
    # Point the link at the real id and make that element focusable.
    map_id_match = re.search(r'<div class="folium-map" id="(map_[a-f0-9]+)"', html_content)
    if map_id_match:
        map_id = map_id_match.group(1)
        html_content = html_content.replace('<a href="#map" ', f'<a href="#{map_id}" ')
        html_content = html_content.replace(
            f'<div class="folium-map" id="{map_id}" >',
            f'<div class="folium-map" id="{map_id}" tabindex="-1">',
        )

    return html_content
